## 추후에 oauth uri, spring db 설정 분리하자
server:
  port: 9090

spring:
  datasource:
    url: 'jdbc:mysql://127.0.0.1:3306/provit?serverTimezone=Asia/Seoul'
    username: 'wz97'
    password: '##wo26dhkttn'

  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: tales0708@gmail.com
    password: payf qgdn kzsy ewyu
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connection-timeout: 5000
          timeout: 5000
          write timeout: 5000
      auth-code-expiration-millis: 900000 #15분

jwt:
  header: Authorization
  secret: porvitrprovitprovitprovitprovitprovitprovitprovitprovitprovitprovitprovit
  token-validity-in-seconds: 30000

OAuth2:
  google:
    ClientId: "71860089687-7sl0ra1430hp1jvm7qj5qckrvgir659s.apps.googleusercontent.com"
    ClientSecret: "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"

    LoginUrl: "https://accounts.google.com/o/oauth2/v2/auth"
    RedirectUrl: "http://localhost:9090/oauth2/redirect_google"
    TokenUrl: "https://oauth2.googleapis.com/token"
    UserInfoUrl: "https://www.googleapis.com/oauth2/v2/userinfo" #헤더에 Authorization: Bearer 토큰 포함해서 사용

  kakao:
    ClientId: "6fdf0f5b44f3d9c1a2e0d315a3420219"
    ClientSeceret: "T6ZSEVyIWVkTQMl6ORhW70NvLTWWpPZw"

    LoginUrl: "https://kauth.kakao.com/oauth/authorize"
    RedirectUrl: "http://localhost:9090/oauth2/redirect_kakao"
    TokenUrl: "https://kauth.kakao.com/oauth/token"
    UserInfoUrl: "https://kapi.kakao.com/v2/user/me"

  naver:
    ClientId: "KsKhLJ05Jk3xES3W2ye_"
    ClientSecret: "fsEQl_xrTK"

    Authorize: "https://nid.naver.com/oauth2.0/authorize"
    Redirect: "http://localhost:9090/oauth2/redirect_naver"
    Token: "https://nid.naver.com/oauth2.0/token"
    UserInfo: "https://openapi.naver.com/v1/nid/me"